[package]
name = "wvwbot-rs"
version = "0.1.0"
authors = ["Greaka <mrgreaka@gmail.com>"]
edition = "2018"

[dependencies]
ratelimit = "0.4.4"
serde = "1.0.87"
serde_derive = "1.0.87"
serde_json = "1.0.38"


[profile.release]
lto = true
codegen-units = 1
